server:
  port: 8084

security:
  oauth2:
    resource:
      jwt:
        key-uri: ${vcap.services.auth-token-key.credentials.uri:http://localhost:9999/auth/oauth/token_key}
#        key-uri: "http://localhost:9999/auth/oauth/token_key"
        
logging:
  level:
    org.springframework.security: DEBUG