server:
  port: 8080
  
logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: INFO
    io.springbox.apigateway: DEBUG
    com.netflix.hystrix: DEBUG
    com.makeurpicks: DEBUG

security:
  oauth2:
    client:
      access-token-uri: ${vcap.services.auth-token.credentials.uri:http://localhost:9999/auth/oauth/token}
      user-authorization-uri: ${vcap.services.auth-authorize.credentials.uri:http://localhost:9999/auth/oauth/authorize}
      client-id: ui
      client-secret: secret
    resource:
      jwt:
        key-value: |
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----

zuul:
#  host:
#    socket-timeout-millis: 5000
  routes:
    league:
      path: /leagues/**
      stripPrefix: false
  #    url: http://localhost:9000
    player:
      path: /register/**
      stripPrefix: true
    pick:
      path: /picks/**
      stripPrefix: false
    season:
      path: /seasons/**
      serviceId: season
      stripPrefix: false
    team:
      path: /teams/**
      serviceId: game
      stripPrefix: false
    week:
      path: /weeks/**
      stripPrefix: false
      serviceId: game
    game:
      path: /games/**
      stripPrefix: false
    leader:
      path: /leaders/**
      stripPrefix: false

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
    

