server:
  port: 8081
#  context-path: /leagues

security:
  oauth2:
    resource:
      jwt:
        key-uri: ${vcap.services.auth-token-key.credentials.uri:http://localhost:9999/auth/oauth/token_key}

logging:
  level:
    com.makeurpicks: DEBUG
#    org.springframework.security: DEBUG