resources:
- name: leagues
  type: git
  source:
    uri: https://github.com/tdelesio/leagues_ms.git
    branch: master
    #private: 8e:f6:81:73:de:45:af:9f:dc:cd:31:bc:06:51:f7:4a
jobs:
- name: build-rc
  plan:
  - get: leagues
    trigger: true
  - task: hello-world
    file: leagues_ms/ci/hello-world.yml

  